### ISSUE TITLE
Implement collaborators

### ISSUE THREAD

**Issue by vramana** [sridhar02/issue-tracker#37]

**Comment by sridhar02** [comment]
- [x] Create a table collaborators with columns repoId and userId 
- [x] get handler to render a collaborator page
- [x] post handler to create a collaborator
- [x] create a html file for collaborators
- [x] create a form element in html
- [x] Checks in post handler are authorization check and whether repoOwner is currentUser. 
- [x] styles 
![image](https://user-images.githubusercontent.com/44333182/61238382-26b80480-a75a-11e9-8e68-54bc4a49b046.png)
- [x] one collaborator can be added one time only
- [x] delete collaborator in html
- [x] delete collaborator handler in server
